# Print The Current Date and Time                       print(datetime.datetime.now())
# Print The Current Year                                print(datetime.datetime.now().year)
# Print The Current Month                               print(datetime.datetime.now().month)
# Print The Current Day                                 print(datetime.datetime.now().day)
# Print The Current Time                                print(datetime.datetime.now().time())
# Print The Current Time Hour                           print(datetime.datetime.now().time().hour)
# Print The Current Time Minute                         print(datetime.datetime.now().time().minute)
# Print The Current Time Second                         print(datetime.datetime.now().time().second)
# Print Specific Date                                   print(datetime.datetime(1982, 10, 25))      print(datetime.datetime(1982, 10, 25, 10, 45, 55, 150364))
# print(myBirthday.strftime("%d - %B - %Y"))
# print(myBirthday.strftime("%d, %B, %Y"))